local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("AdoptHub", "Synapse")
local Tab = Window:NewTab("Ro ka pls")
local Section = Tab:NewSection("Teleport")
Section:NewButton("School","what im do where write?", function()
    print("Click")
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-303,17,-1512)
end)
Section:NewButton("Pet Shop","what im do where write?", function()
    print("Click")
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-191,17,-1508)
end)
Section:NewButton("Pizzeria","what im do where write?", function()
    print("Click")
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-124,17,-1657)
end)
Section:NewButton("Cars Shop","what im do where write?", function()
    print("Click")
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-56,18,-1760)
end)
Section:NewButton("Center","what im do where write?", function()
    print("Click")
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-244,18,-1495)
end)
Section:NewButton("Hospital","what im do where write?", function()
    print("Click")
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-192,17,-1445)
end)
local Tab = Window:NewTab("Discord:vexus!!dd#0057")
